### ISSUE TITLE
If a hyperlink of a page which markdown-preview-enchaced opened is a markdown in localhost, use markdown-preview-enhanced to open it

### ISSUE THREAD

**Issue by Freed-Wu** [weirongxu/coc-markdown-preview-enhanced#23]
**Describe the solution you'd like**
If a hyperlink of a page which markdown-preview-enchaced opened is a markdown in localhost, use markdown-preview-enhanced to open it

That is:

1. Use `:CocCommand markdown-preview-enhanced.openPreview` to open a markdown in browser.
2. In the page which markdown-preview-enhanced opened, there is a hyperlink linked to a markdown in localhost.
3. open this hyperlink in browser.

Actual Bahaviour:

Open `file:///the/path/of/this/markdown/file.md`

Expected Behaviour:

Use `:CocCommand markdown-preview-enhanced.openPreview` to open `/the/path/of/this/markdown/file.md` in browser.

I am not sure is it should be the feature of [upstream](https://github.com/shd101wyy/markdown-preview-enhanced)? If so, I'll transport this issue to upstream.

**Comment by weirongxu** [comment]
I have been busy recently, I will check it in a few days ago

**Comment by weirongxu** [comment]
@Freed-Wu May I ask what the format of your hyperlink actually looks like?
I tested `[name](./filename.md)` and it works.

**Comment by Freed-Wu** [comment]
I have tested `./filename.md` can work and `docs/filename.md` cannot work.
