### ISSUE TITLE
usePandocParser not working

### ISSUE THREAD

**Issue by oblitum** [weirongxu/coc-markdown-preview-enhanced#3]
I tried setting `usePandocParser` to `true` but then just simple markdown text works, math (enclosed with `$`) for example doesn't work.

**Comment by weirongxu** [comment]
It seems this is a bug of markdown-it.

Related Issues:
https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/445#issuecomment-817175826

**Comment by oblitum** [comment]
Okay, thx.
