### ISSUE TITLE
Poor math support

### ISSUE THREAD

**Issue by lygamac** [weirongxu/coc-markdown-preview-enhanced#8]
Compared to [iamco's markdown preview](https://github.com/iamcco/markdown-preview.nvim) in math rendering, extensible characters does not extend themselves and there are missing characters. (Both use KaTeX, so maybe there's some issue with fonts?)

![image](https://user-images.githubusercontent.com/49118209/147754225-27530a58-1487-4663-94cb-4b015d5c86f6.png)

![image](https://user-images.githubusercontent.com/49118209/147754275-d46a0e0b-7acd-4277-96d3-d68a64effd0c.png)

The results are similar in both firefox and chromium.

**Comment by weirongxu** [comment]
I have  fixed it, please upgrade the coc-webview and coc-markdown-preview-enhanced
