### ISSUE TITLE
[BUG] when close preview page, can't open it again without restart vim.

### ISSUE THREAD

**Issue by thelxz** [weirongxu/coc-markdown-preview-enhanced#9]
**Describe the bug**
When close preview page, can't open it again without restart vim.

**Result from CocInfo**

vim version: VIM - Vi IMproved 8.2 8023875
node version: v16.13.1
coc.nvim version: 0.0.80-bd1ad34df2
coc.nvim directory: C:\Users\l00414153\.vim\plugged\coc.nvim
term: undefined
platform: win32

**Steps to reproduce**
1. execute `gvim xxx.md`
2. run `:CocCommand markdown-preview-enhanced.openPreview`
3. Preview tab appear as expect
4. Close preview tab in chrome
4. run  `:CocCommand markdown-preview-enhanced.openPreview` again.
5. **_Preview tab not appear this time._**

**Expected behavior**
Is any method to reopen preview tab without close&restart vim?

**Comment by weirongxu** [comment]
You can also reopen the web page with `:CocList webview`, but I'll fix this too
